export default {
  FAILURE: 'FAILURE',
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
  RESET: 'RESET',
  LOAD_DATA: 'LOAD_DATA',
  LOAD_DATA_SUCCESS: 'LOAD_DATA_SUCCESS',
  SEND_DATA: 'SEND_DATA',
  SEND_DATA_SUCCESS: 'SEND_DATA_SUCCESS',
};
